{
 "title": "Server 1C",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(available_performance,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sessions_data{datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "ALL"
    },
    {
     "expr": "count(sessions_data{appid=\"1CV8C\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "1CV8C"
    },
    {
     "expr": "count(sessions_data{appid=\"1CV8\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "1CV8"
    },
    {
     "expr": "count(sessions_data{appid=\"BackgroundJob\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "BackgroundJob"
    },
    {
     "expr": "count(sessions_data{appid=\"SystemBackgroundJob\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "SystemBackgroundJob"
    },
    {
     "expr": "count(sessions_data{appid=\"WSConnection\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "WSConnection"
    },
    {
     "expr": "count(sessions_data{appid=\"WebClient\",datatype=\"callsall\",quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "WebClient"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (host) (\n  available_performance{instance=\"$instance\", type=\"available\", quantile=\"0.99\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connect",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(connect_sum{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Licence Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(client_lic{quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Duration > 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "count(sessions_data{datatype=\"durationcurrent\",quantile=\"0.99\",instance=\"$instance\"} > 60000)",
     "legendFormat": "durationcurrent"
    }
   ]
  },
  {
   "title": "Long Duration > 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sessions_data{datatype=~\"durationcurrent\", quantile=\"0.99\",instance=\"$instance\"} > 3600000  ",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "AVG Call Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(available_performance{type=\"avgdbcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "DataBase"
    },
    {
     "expr": "avg(available_performance{type=\"avgcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "Call"
    },
    {
     "expr": "avg(available_performance{type=\"avglockcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "Lock"
    }
   ]
  },
  {
   "title": "AVG Call Time Now",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(available_performance{type=\"avgdbcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "Database"
    },
    {
     "expr": "avg(available_performance{type=\"avgcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "Call"
    },
    {
     "expr": "avg(available_performance{type=\"avglockcalltime\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "Lock"
    }
   ]
  },
  {
   "title": "Available Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "available_performance{instance=\"$instance\", type=\"available\", quantile=\"0.99\"}",
     "legendFormat": "{{ host }} {{ pid }}"
    }
   ]
  },
  {
   "title": "Сurrent Memory 1CV8C",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by(value) (3, sessions_data{appid=\"1CV8C\",datatype=\"memorycurrent\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Сurrent Memory BackgroundJob",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by(value) (3, sessions_data{appid=\"BackgroundJob\",datatype=\"memorycurrent\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Сurrent Memory WSConnection",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by(value) (3, sessions_data{appid=\"WSConnection\",datatype=\"memorycurrent\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Сurrent Memory WebClient",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by(value) (3, sessions_data{appid=\"WebClient\",datatype=\"memorycurrent\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk by(value) (10, sessions_data{datatype=\"memorytotal\", quantile=\"0.99\",instance=\"$instance\"})",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}